[package]
name = "sgd2mapi-rs-ffi"
version = "0.1.0"
authors = ["Mir Drualga"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
